

spring:
  application: 
    name: EMS-SYSTEM
  datasource:
    url: jdbc:mysql://localhost:3306/ems_system
    username: root
    password: root
    driver-class-name: "com.mysql.jdbc.Driver"
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
server:
  port: 4001  
   
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      
management.endpoints.web.exposure.include: "*"
    
         
# my.list.values: one,two,three
# listValues: "{field:"value", field2:"valu2"}"